[dev]
  command = "nuxt"

[build]
  command = "nuxt generate"
  publish = "dist"
  functions = "functions"

[[headers]]
  ## Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"